//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.14 at 01:14:52 PM CET 
//


package scp.common.xml.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for optimization complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="optimization">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="shapeid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="coodinates" type="{http://www.stiefels.net/StockCuttingProblem}coordinates"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "optimization", propOrder = {
    "shapeid",
    "coodinates"
})
public class Optimization {

    protected int shapeid;
    @XmlElement(required = true)
    protected Coordinates coodinates;
    @XmlAttribute(required = true)
    protected int id;

    /**
     * Gets the value of the shapeid property.
     * 
     */
    public int getShapeid() {
        return shapeid;
    }

    /**
     * Sets the value of the shapeid property.
     * 
     */
    public void setShapeid(int value) {
        this.shapeid = value;
    }

    /**
     * Gets the value of the coodinates property.
     * 
     * @return
     *     possible object is
     *     {@link Coordinates }
     *     
     */
    public Coordinates getCoodinates() {
        return coodinates;
    }

    /**
     * Sets the value of the coodinates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coordinates }
     *     
     */
    public void setCoodinates(Coordinates value) {
        this.coodinates = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

}
