//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.14 at 01:14:52 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.stiefels.net/StockCuttingProblem")
package scp.common.xml.bindings;
