//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.14 at 01:14:52 PM CET 
//


package scp.common.xml.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for solution complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="solution">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sorting" type="{http://www.stiefels.net/StockCuttingProblem}sorting"/>
 *         &lt;element name="placements" type="{http://www.stiefels.net/StockCuttingProblem}placements"/>
 *         &lt;element name="optimize" type="{http://www.stiefels.net/StockCuttingProblem}optimizations" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "solution", propOrder = {
    "sorting",
    "placements",
    "optimize"
})
public class Solution {

    @XmlElement(required = true)
    protected Sorting sorting;
    @XmlElement(required = true)
    protected Placements placements;
    protected Optimizations optimize;

    /**
     * Gets the value of the sorting property.
     * 
     * @return
     *     possible object is
     *     {@link Sorting }
     *     
     */
    public Sorting getSorting() {
        return sorting;
    }

    /**
     * Sets the value of the sorting property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sorting }
     *     
     */
    public void setSorting(Sorting value) {
        this.sorting = value;
    }

    /**
     * Gets the value of the placements property.
     * 
     * @return
     *     possible object is
     *     {@link Placements }
     *     
     */
    public Placements getPlacements() {
        return placements;
    }

    /**
     * Sets the value of the placements property.
     * 
     * @param value
     *     allowed object is
     *     {@link Placements }
     *     
     */
    public void setPlacements(Placements value) {
        this.placements = value;
    }

    /**
     * Gets the value of the optimize property.
     * 
     * @return
     *     possible object is
     *     {@link Optimizations }
     *     
     */
    public Optimizations getOptimize() {
        return optimize;
    }

    /**
     * Sets the value of the optimize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Optimizations }
     *     
     */
    public void setOptimize(Optimizations value) {
        this.optimize = value;
    }

}
